name: Run Python Script

on:
  schedule:
    # 每3小时执行一次
    - cron: '0 */3 * * *' 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # 指定你需要的Python版本

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run Python script
        run: |
          python ss.py > output.txt
          
      - name: Update README with last run time
        run: |
          sed -i "/<!-- LAST_UPDATE -->/c\Last update: $(date)" README.md
          
      - name: Commit and push output.txt
        run: |
          git config --local user.email "you@example.com"
          git config --local user.name "Your Name"
          git add output.txt
          git commit -m "Add output.txt"
          git push
