name: Run Python Script

on:
  push:
    branches:
      - main  # 当有推送到 main 分支时触发

jobs:
  run-script:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境
    steps:
      - uses: actions/checkout@v2  # 检出代码
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # 使用 Python 3.x 版本
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # 如果有需要安装的依赖库可以在这里添加
          pip install -r requirements.txt
      
      - name: Run Python script
        run: |
          python ss.py  # 运行脚本
      
      - name: Commit and push output.txt
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions"
          git add output.txt
          git commit --allow-empty -m "Add script output"  # 使用 --allow-empty 允许提交空提交
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

